/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elcaro;

import Clases.Campo;
import Clases.Tabla;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Walther
 */
public class guiElcaro extends javax.swing.JFrame {

    /**
     * Creates new form guiElcaro
     */
    public guiElcaro() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCrearArchivo = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txt_crear_archivo_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btChooseFolder = new javax.swing.JButton();
        jlCarpetaCrearArchivo = new javax.swing.JLabel();
        btCrearArchivo = new javax.swing.JButton();
        jdPrincipal = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistTablas = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        jlNombreDB = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btCrearCampo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jdCrearCampo = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfCrearCampoNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sp_agreg_campo = new javax.swing.JSpinner();
        btAgregarCrearCampo = new javax.swing.JButton();
        jd_Configuracion = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rb_config_var = new javax.swing.JRadioButton();
        rb_config_fija = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        txt_config_nom = new javax.swing.JTextField();
        btn_config_crear_db = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btNuevoDB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btAbrirDB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btBorrarDB = new javax.swing.JButton();
        btLockDB = new javax.swing.JButton();
        btNuevoDB3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/663px-Oracle_logo_opt.png"))); // NOI18N

        txt_crear_archivo_nombre.setBackground(new java.awt.Color(204, 204, 204));
        txt_crear_archivo_nombre.setText("database.pitydb");

        jLabel8.setText("Nombre del archivo:");

        btChooseFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder.png"))); // NOI18N
        btChooseFolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btChooseFolderMouseClicked(evt);
            }
        });

        btCrearArchivo.setBackground(new java.awt.Color(255, 255, 255));
        btCrearArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearFolder.png"))); // NOI18N
        btCrearArchivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCrearArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearArchivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdCrearArchivoLayout = new javax.swing.GroupLayout(jdCrearArchivo.getContentPane());
        jdCrearArchivo.getContentPane().setLayout(jdCrearArchivoLayout);
        jdCrearArchivoLayout.setHorizontalGroup(
            jdCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearArchivoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jdCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jlCarpetaCrearArchivo)
                    .addGroup(jdCrearArchivoLayout.createSequentialGroup()
                        .addComponent(txt_crear_archivo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btChooseFolder))
                    .addComponent(btCrearArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jdCrearArchivoLayout.setVerticalGroup(
            jdCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearArchivoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearArchivoLayout.createSequentialGroup()
                        .addGroup(jdCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btChooseFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_crear_archivo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCarpetaCrearArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCrearArchivo))
                    .addComponent(jLabel7))
                .addGap(30, 30, 30))
        );

        jScrollPane1.setViewportView(jlistTablas);

        jLabel9.setText("TABLAS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ID"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setText("REGISTROS");

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btSave.setBorder(null);
        btSave.setBorderPainted(false);

        jlNombreDB.setText("jLabel11");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearTabla.png"))); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar Campo");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btCrearCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearCampo.png"))); // NOI18N
        btCrearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCrearCampoMouseClicked(evt);
            }
        });

        jLabel12.setText("Crear Tabla");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevoRegistro.png"))); // NOI18N

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nuevo Registro");

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal.getContentPane());
        jdPrincipal.getContentPane().setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jdPrincipalLayout.createSequentialGroup()
                .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdPrincipalLayout.createSequentialGroup()
                        .addComponent(btSave)
                        .addGap(445, 445, 445)
                        .addComponent(jlNombreDB))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdPrincipalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9)
                        .addGap(467, 467, 467)
                        .addComponent(jLabel10))
                    .addGroup(jdPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jdPrincipalLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)))
                        .addGap(19, 19, 19)
                        .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCrearCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdPrincipalLayout.createSequentialGroup()
                .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSave)
                    .addGroup(jdPrincipalLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jlNombreDB)))
                .addGap(6, 6, 6)
                .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdPrincipalLayout.createSequentialGroup()
                        .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jdPrincipalLayout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdPrincipalLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdPrincipalLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(3, 3, 3)
                                .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)))
                            .addComponent(btCrearCampo))))
                .addGap(6, 6, 6)
                .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crearCampo.png"))); // NOI18N

        jLabel14.setText("Nombre:");

        jLabel15.setText("Tamaño:");

        btAgregarCrearCampo.setText("AGREGAR!");
        btAgregarCrearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgregarCrearCampoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jdCrearCampoLayout = new javax.swing.GroupLayout(jdCrearCampo.getContentPane());
        jdCrearCampo.getContentPane().setLayout(jdCrearCampoLayout);
        jdCrearCampoLayout.setHorizontalGroup(
            jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(32, 32, 32)
                .addGroup(jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearCampoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCrearCampoNombre))
                    .addGroup(jdCrearCampoLayout.createSequentialGroup()
                        .addGroup(jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAgregarCrearCampo)
                            .addGroup(jdCrearCampoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_agreg_campo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jdCrearCampoLayout.setVerticalGroup(
            jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tfCrearCampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sp_agreg_campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btAgregarCrearCampo)
                .addGap(21, 21, 21))
        );

        jLabel17.setText("CONFIGURACION");

        jLabel18.setText("Longitud de Campo:");

        buttonGroup1.add(rb_config_var);
        rb_config_var.setText("Variable");

        buttonGroup1.add(rb_config_fija);
        rb_config_fija.setSelected(true);
        rb_config_fija.setText("Fija");

        jLabel21.setText("Nombre del archivo:");

        btn_config_crear_db.setText("Crear Archivo");
        btn_config_crear_db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_config_crear_dbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ConfiguracionLayout = new javax.swing.GroupLayout(jd_Configuracion.getContentPane());
        jd_Configuracion.getContentPane().setLayout(jd_ConfiguracionLayout);
        jd_ConfiguracionLayout.setHorizontalGroup(
            jd_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ConfiguracionLayout.createSequentialGroup()
                .addGroup(jd_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ConfiguracionLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel17))
                    .addGroup(jd_ConfiguracionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(rb_config_fija)
                        .addGap(10, 10, 10)
                        .addComponent(rb_config_var)))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(jd_ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jd_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_config_crear_db)
                    .addComponent(txt_config_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_ConfiguracionLayout.setVerticalGroup(
            jd_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rb_config_var)
                    .addComponent(rb_config_fija))
                .addGap(18, 18, 18)
                .addGroup(jd_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_config_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_config_crear_db)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/663px-Oracle_logo.svg.png"))); // NOI18N

        btNuevoDB.setBackground(new java.awt.Color(255, 255, 255));
        btNuevoDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dbNew.png"))); // NOI18N
        btNuevoDB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btNuevoDB.setBorderPainted(false);
        btNuevoDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNuevoDB.setName(""); // NOI18N
        btNuevoDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNuevoDBMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Create New DB");

        btAbrirDB.setBackground(new java.awt.Color(255, 255, 255));
        btAbrirDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dbOpen.png"))); // NOI18N
        btAbrirDB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAbrirDB.setBorderPainted(false);
        btAbrirDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAbrirDB.setName(""); // NOI18N
        btAbrirDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAbrirDBMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Open DB");

        btBorrarDB.setBackground(new java.awt.Color(255, 255, 255));
        btBorrarDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dbErase.png"))); // NOI18N
        btBorrarDB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btBorrarDB.setBorderPainted(false);
        btBorrarDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBorrarDB.setName(""); // NOI18N
        btBorrarDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBorrarDBMouseClicked(evt);
            }
        });

        btLockDB.setBackground(new java.awt.Color(255, 255, 255));
        btLockDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dbLock.png"))); // NOI18N
        btLockDB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btLockDB.setBorderPainted(false);
        btLockDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLockDB.setName(""); // NOI18N

        btNuevoDB3.setBackground(new java.awt.Color(255, 255, 255));
        btNuevoDB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dbInfo.png"))); // NOI18N
        btNuevoDB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btNuevoDB3.setBorderPainted(false);
        btNuevoDB3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNuevoDB3.setName(""); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Erase DB");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Lock DB");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("HELP!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBorrarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLockDB, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNuevoDB, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAbrirDB, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btNuevoDB3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel6)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(btNuevoDB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btAbrirDB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btBorrarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLockDB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addComponent(btNuevoDB3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BT Crear DB Menu Principal
    private void btNuevoDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNuevoDBMouseClicked
        jdCrearArchivo.getContentPane().setBackground(Color.WHITE);
        jdCrearArchivo.setModal(true);
        jdCrearArchivo.pack();
        jdCrearArchivo.setLocationRelativeTo(null);
        jdCrearArchivo.setVisible(true);
    }//GEN-LAST:event_btNuevoDBMouseClicked

    //BT Crear Campo
    private void btCrearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearCampoMouseClicked
        jdCrearCampo.getContentPane().setBackground(Color.WHITE);
        jdCrearCampo.setModal(true);
        jdCrearCampo.pack();
        jdCrearCampo.setLocationRelativeTo(null);
        jdCrearCampo.setVisible(true);
    }//GEN-LAST:event_btCrearCampoMouseClicked

    //BT Obtener Carpeta donde se trabajara
    private void btChooseFolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btChooseFolderMouseClicked
        File f;
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jf.showOpenDialog(this);
        f = jf.getSelectedFile();
        jlCarpetaCrearArchivo.setText(f.getPath());
    }//GEN-LAST:event_btChooseFolderMouseClicked

    //BT Crear Archivo
    private void btCrearArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCrearArchivoMouseClicked
//        System.out.println("BT CREAR ARCHIVO");
//        System.out.println("Aqui debe hacer una tabla nueva");
//        System.out.println("La tabla la debe agregar a la JList");
//        System.out.println("La tabla por default debe traer un campo ID");
//        System.out.println("Aqui se pregunta si quiere que sea longitud variable o fija");
        System.out.println("Al mismo tiempo debe actualizarse la JTable que esta en la principal");
//        System.out.println("Tambien este muestra el jdialog principal");
//        System.out.println("Recordar hacer setModal, Pack, SetLocationRelativeTo(null), setVisible");
        txt_config_nom.setText(txt_crear_archivo_nombre.getText());
        jd_Configuracion.setModal(true);
        jd_Configuracion.pack();
        jd_Configuracion.setLocationRelativeTo(null);
        jd_Configuracion.setVisible(true);

    }//GEN-LAST:event_btCrearArchivoMouseClicked

    
    //BT para configurar la creacion de la BD
    private void btn_config_crear_dbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_config_crear_dbMouseClicked
        // TODO add your handling code here:
        String tipo = "";
        if (rb_config_fija.isSelected()) {
            tipo = "Fijo";
        } else {
            tipo = "Variable";
        }
        String nombre = txt_config_nom.getText() + ".pitydb";
        String nom_campo = "ID";
        int longitud = 5;
        campos.add(new Campo(nom_campo, longitud, "String"));
        //tablas.add(new Tabla("Tabla 1", campos, 0));
        File archivo;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File(nombre);
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            bw.write(tipo + ",");
            bw.flush();
            JOptionPane.showMessageDialog(null, "Archivo creado correctamente");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (IOException ex) {
            }
        }
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < tablas.size(); i++) {
            modelo.addElement(tablas.get(i).getNombre());
        }
        jlistTablas.setModel(modelo);
        jdPrincipal.setModal(true);
        jdPrincipal.pack();
        jdPrincipal.setLocationRelativeTo(null);
        jdPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_config_crear_dbMouseClicked

    
    //BT para abrir una bd
    private void btAbrirDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAbrirDBMouseClicked
        // TODO add your handling code here:
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Base de Datos", "pitydb");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);
                br = new BufferedReader(fr);
                String linea;
//                while((linea=br.readLine())!=null){
//                    ta_1.append(linea+"\n");
//                }
            } else {
                JOptionPane.showMessageDialog(null, "Archivo no valido");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btAbrirDBMouseClicked
    

    //BT para borrar una base de datos
    private void btBorrarDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBorrarDBMouseClicked
        // TODO add your handling code here:
        boolean bl = false;
        File fichero = null;
        JFileChooser jfc = new JFileChooser();
        try {
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Base de Datos", "pitydb");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fichero.delete();
                bl = true;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        if (bl == true) {
            JOptionPane.showMessageDialog(null,"Archivo Borrado");
        } else {
            JOptionPane.showMessageDialog(null,"No se pudo borrar archivo");
        }


    }//GEN-LAST:event_btBorrarDBMouseClicked

    //BT para agregar un campo nuevo a una tabla
    private void btAgregarCrearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarCrearCampoMouseClicked
        // TODO add your handling code here:
        String nom_campo=tfCrearCampoNombre.getText();
        int longitud= (int) sp_agreg_campo.getValue();
    }//GEN-LAST:event_btAgregarCrearCampoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiElcaro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiElcaro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiElcaro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiElcaro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiElcaro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirDB;
    private javax.swing.JButton btAgregarCrearCampo;
    private javax.swing.JButton btBorrarDB;
    private javax.swing.JButton btChooseFolder;
    private javax.swing.JButton btCrearArchivo;
    private javax.swing.JButton btCrearCampo;
    private javax.swing.JButton btLockDB;
    private javax.swing.JButton btNuevoDB;
    private javax.swing.JButton btNuevoDB3;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btn_config_crear_db;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jdCrearArchivo;
    private javax.swing.JDialog jdCrearCampo;
    private javax.swing.JDialog jdPrincipal;
    private javax.swing.JDialog jd_Configuracion;
    private javax.swing.JLabel jlCarpetaCrearArchivo;
    private javax.swing.JLabel jlNombreDB;
    private javax.swing.JList jlistTablas;
    private javax.swing.JRadioButton rb_config_fija;
    private javax.swing.JRadioButton rb_config_var;
    private javax.swing.JSpinner sp_agreg_campo;
    private javax.swing.JTextField tfCrearCampoNombre;
    private javax.swing.JTextField txt_config_nom;
    private javax.swing.JTextField txt_crear_archivo_nombre;
    // End of variables declaration//GEN-END:variables
    public static ArrayList<Tabla> tablas = new ArrayList();
    public static ArrayList<Campo> campos = new ArrayList();

}
